app:
  build: .
  command: python3 -u run.py $SETUP_DB $PRODUCTION /data/
  # stdin_open: true
  # tty: true
  ports:
   - "5000:5000"
  volumes:
   - .:/code
   - "$DATA_FOLDER_PATH:/data/"
  environment:
   - LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib
  links:
    - db
db:
  image: mongo:3.4.6
